name: 'Lint Security Insights'
description: >
  Use cue to validate a given security insights file
  against the Security Insights schema.
branding:
  icon: check
  color: green

inputs:
  si-path:
    description: 'Path to security-insights.yml'
    required: false
    default: 'security-insights.yml'
  schema-version:
    description: 'Version of the Security Insights schema to use'
    required: false
    default: 'v2.1.0'
  skip-cue-setup:
    description: 'Run setup-cue (defaults to true)'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - if: ${{ inputs.skip-cue-setup == 'false' }}
      uses: cue-lang/setup-cue@a93fa358375740cd8b0078f76355512b9208acb1 # v1.0.1

    - name: Lint security-insights.yml
      shell: bash
      env:
        VERSION: ${{ inputs.schema-version }}
        SI_PATH: ${{ inputs.si-path }}
      run: |
        echo "::group::Linting ${SI_PATH} ..."
        make lintinsights -f "${GITHUB_ACTION_PATH}/Makefile"
        echo "::endgroup::"
